#!/bin/bash

export MIGDIS_ENABLE=${MIGDIS_ENABLE:-True}
export MIGDIS_GRAD_EMA_BETA=${MIGDIS_GRAD_EMA_BETA:-0.95}
export MIGDIS_GRAD_MIX=${MIGDIS_GRAD_MIX:-0.50}
export MIGDIS_SOURCE_MARGIN=${MIGDIS_SOURCE_MARGIN:-0.35}
export MIGDIS_SOURCE_SCOPE=${MIGDIS_SOURCE_SCOPE:-qkv}
export MIGDIS_NORM=${MIGDIS_NORM:-robust}
export MIGDIS_NORM_Q_LOW=${MIGDIS_NORM_Q_LOW:-0.05}
export MIGDIS_NORM_Q_HIGH=${MIGDIS_NORM_Q_HIGH:-0.95}
export MIGDIS_EPS=${MIGDIS_EPS:-1e-6}
export MIGDIS_SOURCE_CHUNK_ROWS=${MIGDIS_SOURCE_CHUNK_ROWS:-2048}
export MIGDIS_FINAL_GAMMA=${MIGDIS_FINAL_GAMMA:-1.0}
export MIGDIS_DEBUG_DUMP=${MIGDIS_DEBUG_DUMP:-True}
export RUN_NAME=${RUN_NAME:-llava-v1.5-7b-lorasculpt-migdis-iconqa-r32}
