#!/bin/bash

export PARS_ENABLE=${PARS_ENABLE:-True}
export PARS_PROJECTOR_LAMBDA=${PARS_PROJECTOR_LAMBDA:-20.0}
export PARS_PROJECTOR_TAU=${PARS_PROJECTOR_TAU:-0.020}
export PARS_PROJECTOR_WARMUP_STEPS=${PARS_PROJECTOR_WARMUP_STEPS:-100}
export PARS_STABLE_RANK=${PARS_STABLE_RANK:-8}
export PARS_STABLE_LR_MULT=${PARS_STABLE_LR_MULT:-0.25}
export PARS_ORTH_LAMBDA=${PARS_ORTH_LAMBDA:-0.01}
export PARS_LOG_EVERY=${PARS_LOG_EVERY:-20}
export PARS_EPS=${PARS_EPS:-1e-8}

export MIGDIS_ENABLE=${MIGDIS_ENABLE:-False}
export MIGDIS_GRAD_EMA_BETA=${MIGDIS_GRAD_EMA_BETA:-0.95}
export MIGDIS_GRAD_MIX=${MIGDIS_GRAD_MIX:-0.50}
export MIGDIS_SOURCE_MARGIN=${MIGDIS_SOURCE_MARGIN:-0.35}
export MIGDIS_SOURCE_SCOPE=${MIGDIS_SOURCE_SCOPE:-qkv}
export MIGDIS_NORM=${MIGDIS_NORM:-robust}
export MIGDIS_EPS=${MIGDIS_EPS:-1e-6}
export MIGDIS_FINAL_GAMMA=${MIGDIS_FINAL_GAMMA:-1.0}
export MIGDIS_DEBUG_DUMP=${MIGDIS_DEBUG_DUMP:-True}
export MIGDIS_SELECTION_MODE=${MIGDIS_SELECTION_MODE:-global}

export SMOKE_MAX_STEPS=${SMOKE_MAX_STEPS:-20}
export RUN_NAME=${RUN_NAME:-llava-v1.5-7b-lorasculpt-pars-B-balanced-r32}
